### ISSUE TITLE
Can't save credit card info

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/bridge-gui#96]
When i enter all of my payment details in "Billing" and hit "save credit card" nothing happens, i can click on the box as much as i like, it doesn't do anything and my credit card info is not saved.

**Comment by tempestb** [comment]
To back what Meije is stating...

  When I connect with https the balances of 0.0000000 are sometimes not appearing.  This throws various errors in the console.  Apollo error, graph error, etc.

  When I connect with http the balances of 0.0000000 are showing properly.   When submitting a credit card number, however, an error in the console appears that states, "402 (Payment Required)"   The number has been filled in.  

It's my guess that the payment doesn't work because it needs to charge something, and it is unable to do so because the balances are zero.  Just a guess though.

**Comment by bryanchriswhite** [comment]
@MeijeSibbel you somehow managed to get 2 `paymentprocessors` in the db but it's likely due to the state of the rollout when you tried to add a payment method. I've since deleted the few invalid `paymentprocessor` documents that existed. I would love to hear back from you after trying again. 

Also @MeijeSibbel, what browser/OS are you using - just to be thorough.

@tempestb thanks for the additional data! This led me to discover that when you switch between http and https versions of the gui, the "origin" changes (for same-origin purposes). This means the `privkey` localstorage key can get lost. Consequently the gui isn't able to auth it's requests to billing via ECDSA and we're currently not redirecting back to the login page.

I plan to fix this by redirecting to login if api request fail with 4xx statuses.

(also, I recommend the https everywhere extension/plugin https://www.eff.org/https-everywhere%20)

**Comment by Th3Van** [comment]
I also tried to add my VISA (using https), but just like @MeijeSibbel nothing happens when 
hitting **"Save Credit Card"**.
But changing only the CC number to any of the three VISA test cards on this PayPallobject list, the card seems to be  accepted..
_https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm_

Username : th3van@bodata.dk
OS : Windows 2012 R2 server w/ Firefox 50.1.0

//Th3van

**Comment by bryanchriswhite** [comment]
Ok guys.. I think @barbaraliau and I sorted it.

> Genuine card information cannot be used in test mode. 
--Stripe (https://stripe.com/docs/testing#cards)

This seems to be a feature :P

**Comment by MeijeSibbel** [comment]
@bryanchriswhite , it is still not working for me (same issue): windows 10, google chrome

**Comment by Th3Van** [comment]
I think "we" are still in test mode, so (as i understand it) it won't work with Genuine CC cards until the team puts it in production mode.

I hope this will happen soon:tm: 😃 

//Th3Van

**Comment by MeijeSibbel** [comment]
Alright, i will wait :)

**Comment by MeijeSibbel** [comment]
LOL, i can't even add a fake credit card number...

**Comment by barbaraliau** [comment]
@MeijeSibbel Try 4242424242424242. That one usually works for me. As far as test CC numbers go.

**Comment by MeijeSibbel** [comment]
@barbaraliau , Still no luck with that number, also, why doesn't the postal code field accept a valid code (e.g. 3999NP for my Dutch residence and 3530-027 for my Portuguese residence)?

**Comment by MeijeSibbel** [comment]
![2017-02-01](https://cloud.githubusercontent.com/assets/11735738/22529546/bcf87b56-e8cf-11e6-929a-44f3da1967b6.png)

**Comment by barbaraliau** [comment]
@MeijeSibbel Try doing the Credit Card with an expiration of 02/2020. I just took a look and it looks like we need to change the type for zip code. I'll open up an issue for it and we'll get it fixed.

**Comment by MeijeSibbel** [comment]
@barbaraliau , same thing, it does not work ( i tried that before though - 02/2020)

**Comment by barbaraliau** [comment]
@MeijeSibbel ok. I'll look into it a little more.

**Comment by MeijeSibbel** [comment]
HTML5 validation:
```
Warning: Content-Security-Policy HTTP header: Bad content security policy: The frame-src directive is deprecated as of CSP version 1.1. Authors who wish to govern nested browsing contexts SHOULD use the child-src directive instead.
https://app.storj.io/?_k=2ial2f
Error: Element title must not be empty.
From line 2, column 182; to line 2, column 189
fc.0.1:$"></title><link 
Error: Bad value screen, projection for attribute media on element link: Deprecated media type projection. For guidance, see the Media Types section in the current Media Queries specification.
From line 2, column 370; to line 2, column 527
cfc.0.6"/><link href="/dist/main-d6b0429660237be753a8.css" media="screen, projection" rel="stylesheet" type="text/css" charset="UTF-8" data-reactid=".1df56p02cfc.0.7"/><scrip
Error: The charset attribute on the link element is obsolete. Use an HTTP Content-Type header on the linked resource instead.
From line 2, column 370; to line 2, column 527
cfc.0.6"/><link href="/dist/main-d6b0429660237be753a8.css" media="screen, projection" rel="stylesheet" type="text/css" charset="UTF-8" data-reactid=".1df56p02cfc.0.7"/><scrip
```

**Comment by barbaraliau** [comment]
@bryanchriswhite ^^^ I haven't been able to reproduce this. Have you seen this in any testing you've done?

**Comment by MeijeSibbel** [comment]
<!doctype html>
<html lang="en-us" data-reactid=".1tbvq9xflf8" data-react-checksum="942870577"><head data-reactid=".1tbvq9xflf8.0"><title data-react-helmet="true" data-reactid=".1tbvq9xflf8.0.1:$"></title><link rel="shortcut icon" href="/favicon.ico" data-reactid=".1tbvq9xflf8.0.5"/><meta name="viewport" content="width=device-width, initial-scale=1" data-reactid=".1tbvq9xflf8.0.6"/><link href="/dist/main-d6b0429660237be753a8.css" media="screen, projection" rel="stylesheet" type="text/css" charset="UTF-8" data-reactid=".1tbvq9xflf8.0.7"/><script type="text/javascript" src="https://js.stripe.com/v2/" data-reactid=".1tbvq9xflf8.0.8"></script></head><body data-reactid=".1tbvq9xflf8.1"><div id="content" data-reactid=".1tbvq9xflf8.1.0"></div><script src="/dist/main-d6b0429660237be753a8.js" charset="UTF-8" data-reactid=".1tbvq9xflf8.1.1"></script></body></html>

**Comment by tempestb** [comment]
I also see the deprecation warning in the console of Firefox.  

Like Meije, I've tried various numbers both legit and fake from the list of fake numbers, and nothing happens.  

Well...  Something happens.  I frown for a moment, and then I daydream about warmer weather and going outside to enjoy the day.  Eventually someone asks me a question and I snap out of it.  So there is that, but it is unrelated to the Billing as a whole.

**Comment by Th3Van** [comment]
I'm still able to create a test card using these infos (th3van@bodata.dk) :

![cc 1](https://cloud.githubusercontent.com/assets/18688983/22536144/d4a17b42-e8ff-11e6-807f-a1e8d9742322.png)


*And they turn out to this* : 


![cc 2](https://cloud.githubusercontent.com/assets/18688983/22536146/d9bc8946-e8ff-11e6-8a26-984cb9fb444c.png)

**Comment by bryanchriswhite** [comment]
Reopening this cos there's apparently still something up here - looking into it. Thank everyone for all the feedback, it's super useful.

**Comment by bryanchriswhite** [comment]
@MeijeSibbel, @barbaraliau I wasn't able to reproduce @MeijeSibbel's issue regarding the CSP, `title` or `link` elements... but I did have look at MDN's documentation on CSP as it relates to `frame-src` vs `child-src` and it's a bit convoluted. Bottom-line on CSP, I'd like to *add* `child-src` and see if @MeijeSibbel still gets the CSP error again using the same browser/OS combo. _BTW I did test this using chrome 55 on windoze 10._

**Comment by bryanchriswhite** [comment]
@tempestb which email are you using with your storj account, so I can look for your payment processor(s) in the db?

**Comment by tempestb** [comment]
I have been trying two emails...

tempestc at hotmail.com
Storj16 at videogamenews.com

**Comment by bryanchriswhite** [comment]
Alright guys, I have new explanation for what's happening...

The **first** time you add a card (i.e. you don't have a paymentprocessor document or stripe customer yet), a slightly different bit of logic happens when compared to adding a card back (for any subsequent time; i.e. you **do** have a paymentprocessor document and a stripe customer).

If the **first** card you try to add is a real card, your user gets stuck in a state that fits exactly the behavior we're seeing here with respect to adding a card (CSP stuff aside). From this state, you can't add either real or fake cards. This is a bug.

**Comment by bryanchriswhite** [comment]
Once fixed, I'll wipe all the invalid paymentprocessors again and make an announcement in community chat.

**Comment by MeijeSibbel** [comment]
Glad you found the issue @bryanchriswhite !
